package solutions

// Even Fibonacci numbers

// Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
// 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
// By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

import "fmt"

const maxFib = 4000000

func fib() int {
	a := 1
	b := 1
	var c int
	var sum int

	for i:=0; c<maxFib; i++ {
		c = a + b
		if c&1 == 0 {
			sum += c
		}
		a = b
		b = c
	}
	return sum
}

func Sol2() {
	ans := fib()
	fmt.Printf("Answer to problem 2 = %d \n", ans)
}